global:
  scrape_interval: 15s # By default, scrape targets every 15seconds. # Attach these labels to any time series or alerts when #communicating with external systems (federation, remote storage, #Alertmanager).
  # external_labels:
  #   monitor: 'codelab-monitor'
# Scraping Prometheus itself
scrape_configs:
- job_name: 'prometheus'
  scrape_interval: 5s
  static_configs:
  - targets: ['localhost:9090']
- job_name: 'kubernetes-nodes'
  kubernetes_sd_configs:
  - role: node
  relabel_configs:
  - action: labelmap
    regex: __meta_kubernetes_node_label_(.+)
- job_name: 'kubernetes-pods'
  kubernetes_sd_configs:
  - role: pod
  relabel_configs:
  - action: labelmap
    regex: __meta_kubernetes_pod_label_(.+)
  - source_labels: [__meta_kubernetes_namespace]
    action: replace
    target_label: kubernetes_namespace
  - source_labels: [__meta_kubernetes_pod_name]
    action: replace
    target_label: kubernetes_pod_name
- job_name: 'kubernetes-service-endpoints'
  kubernetes_sd_configs:
  - role: endpoints
  relabel_configs:
  - action: labelmap
    regex: __meta_kubernetes_service_label_(.+)
  - source_labels: [__meta_kubernetes_namespace]
    action: replace
    target_label: kubernetes_namespace
  - source_labels: [__meta_kubernetes_service_name]
    action: replace
    target_label: kubernetes_name
# - job_name: 'kubernetes-services'
#   metrics_path: /probe
#   params:
#     module: [http_2xx]
#   kubernetes_sd_configs:
#   - role: service
#   relabel_configs:
#   # Example relabel to probe only some services that have "example.io/should_be_probed = true" annotation
#   #  - source_labels: [__meta_kubernetes_service_annotation_example_io_should_be_probed]
#   #    action: keep
#   #    regex: true
#   - source_labels: [__address__]
#     target_label: __param_target
#   - target_label: __address__
#     replacement: blackbox-exporter.example.com:9115
#   - source_labels: [__param_target]
#     target_label: instance
#   - action: labelmap
#     regex: __meta_kubernetes_service_label_(.+)
#   - source_labels: [__meta_kubernetes_namespace]
#     target_label: kubernetes_namespace
#   - source_labels: [__meta_kubernetes_service_name]
#     target_label: kubernetes_name
# - job_name: 'kubernetes-ingresses'
#   metrics_path: /probe
#   params:
#     module: [http_2xx]
#   kubernetes_sd_configs:
#   - role: ingress
#   relabel_configs:
#   # Example relabel to probe only some ingresses that have "example.io/should_be_probed = true" annotation
#   #  - source_labels: [__meta_kubernetes_ingress_annotation_example_io_should_be_probed]
#   #    action: keep
#   #    regex: true
#   - source_labels: [__meta_kubernetes_ingress_scheme,__address__,__meta_kubernetes_ingress_path]
#     regex: (.+);(.+);(.+)
#     replacement: ${1}://${2}${3}
#     target_label: __param_target
#   - target_label: __address__
#     replacement: blackbox-exporter.example.com:9115
#   - source_labels: [__param_target]
#     target_label: instance
#   - action: labelmap
#     regex: __meta_kubernetes_ingress_label_(.+)
#   - source_labels: [__meta_kubernetes_namespace]
#     target_label: kubernetes_namespace
#   - source_labels: [__meta_kubernetes_ingress_name]
#     target_label: kubernetes_name

