kind: Deployment
apiVersion: apps/v1
metadata:
  name: nfs-pod-provisioner
  # namespace: storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-pod-provisioner
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-pod-provisioner
    spec:
      serviceAccountName: nfs-pod-provisioner-sa
      containers:
        - name: nfs-pod-provisioner
          image: quay.io/external_storage/nfs-client-provisioner:latest
          volumeMounts:
            - name: nfs-provisioner-v
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: nfs-provisioner
            - name: NFS_SERVER
              value: 172.18.0.5
            - name: NFS_PATH
              value: /
      volumes:
       - name: nfs-provisioner-v # same as volumemouts name
         nfs:
           server: 172.18.0.5
           path: /
